# NLP Assignment 5: Fine-Tuning BERT for POS Tagging & Chunking

**Model:** DistilBERT (lightweight, fast)  
**Dataset:** CoNLL-2003 (Chunking)  
**Tasks:** POS Tagging + Chunking via Token Classification

In [19]:
!pip install transformers datasets seqeval -q

In [20]:
from datasets import load_dataset

dataset = load_dataset("surrey-nlp/PLOD-CW")

print("Dataset Structure:")
print(dataset)
print("\nSample Entry:")
print(dataset["train"][0])

Dataset Structure:
DatasetDict({
    train: Dataset({
        features: ['tokens', 'pos_tags', 'ner_tags'],
        num_rows: 1072
    })
    validation: Dataset({
        features: ['tokens', 'pos_tags', 'ner_tags'],
        num_rows: 126
    })
    test: Dataset({
        features: ['tokens', 'pos_tags', 'ner_tags'],
        num_rows: 153
    })
})

Sample Entry:
{'tokens': ['For', 'this', 'purpose', 'the', 'Gothenburg', 'Young', 'Persons', 'Empowerment', 'Scale', '(', 'GYPES', ')', 'was', 'developed', '.'], 'pos_tags': ['ADP', 'DET', 'NOUN', 'DET', 'PROPN', 'PROPN', 'PROPN', 'PROPN', 'PROPN', 'PUNCT', 'PROPN', 'PUNCT', 'AUX', 'VERB', 'PUNCT'], 'ner_tags': ['B-O', 'B-O', 'B-O', 'B-O', 'B-LF', 'I-LF', 'I-LF', 'I-LF', 'I-LF', 'B-O', 'B-AC', 'B-O', 'B-O', 'B-O', 'B-O']}

In [21]:
# Extract unique string labels directly from the data
all_pos_tags   = set(tag for row in dataset["train"]["pos_tags"] for tag in row)
all_chunk_tags = set(tag for row in dataset["train"]["ner_tags"] for tag in row)

# Sort for stable index ordering
pos_label_names   = sorted(all_pos_tags)
chunk_label_names = sorted(all_chunk_tags)

# Build id↔label mappings
pos_label2id   = {label: i for i, label in enumerate(pos_label_names)}
pos_id2label   = {i: label for i, label in enumerate(pos_label_names)}
chunk_label2id = {label: i for i, label in enumerate(chunk_label_names)}
chunk_id2label = {i: label for i, label in enumerate(chunk_label_names)}

print(f"POS Tag Labels ({len(pos_label_names)} total):")
print(pos_label_names)
print(f"\nChunk/NER Tag Labels ({len(chunk_label_names)} total):")
print(chunk_label_names)

POS Tag Labels (17 total):
['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X']

Chunk/NER Tag Labels (4 total):
['B-AC', 'B-LF', 'B-O', 'I-LF']

In [22]:
TRAIN_SIZE = min(100, len(dataset["train"]))
VAL_SIZE   = min(50,  len(dataset["validation"]))

small_train = dataset["train"].shuffle(seed=42).select(range(TRAIN_SIZE))
small_val   = dataset["validation"].shuffle(seed=42).select(range(VAL_SIZE))

print(f"Training samples  : {len(small_train)}")
print(f"Validation samples: {len(small_val)}")

Training samples  : 100
Validation samples: 50

In [23]:
from transformers import AutoTokenizer

MODEL_CHECKPOINT = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)

print(f"Tokenizer loaded: {MODEL_CHECKPOINT}")

# Demo: see subword tokenization in action
sample_words = dataset["train"][0]["tokens"]
print(f"\nOriginal words : {sample_words}")
tokenized = tokenizer(sample_words, is_split_into_words=True)
print(f"Subword tokens : {tokenizer.convert_ids_to_tokens(tokenized['input_ids'])}")
print(f"Word IDs       : {tokenized.word_ids()}")

Tokenizer loaded: distilbert-base-uncased

Original words : ['For', 'this', 'purpose', 'the', 'Gothenburg', 'Young', 'Persons', 'Empowerment', 'Scale', '(', 'GYPES', ')', 'was', 'developed', '.']
Subword tokens : ['[CLS]', 'for', 'this', 'purpose', 'the', 'gothenburg', 'young', 'persons', 'empowerment', 'scale', '(', 'g', '##ype', '##s', ')', 'was', 'developed', '.', '[SEP]']
Word IDs       : [None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 11, 12, 13, 14, None]

In [24]:
def tokenize_and_align_labels(examples, label_column, label2id):
    """
    Tokenizes input and aligns string labels to subword tokens.
    - First subword of each word  → real label (converted to int)
    - Continuation subwords       → -100 (ignored by loss)
    - Special tokens [CLS],[SEP]  → -100
    """
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True,
        max_length=128,
        padding="max_length"
    )

    all_labels = []
    for i, label_list in enumerate(examples[label_column]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        aligned_labels = []
        previous_word_id = None

        for word_id in word_ids:
            if word_id is None:
                aligned_labels.append(-100)
            elif word_id != previous_word_id:
                aligned_labels.append(label2id[label_list[word_id]])
            else:
                aligned_labels.append(-100)
            previous_word_id = word_id

        all_labels.append(aligned_labels)

    tokenized_inputs["labels"] = all_labels
    return tokenized_inputs

print("Preprocessing function defined.")

Preprocessing function defined.

In [37]:
import functools

# Chunking (NER tags — BIO span detection)
chunk_fn  = functools.partial(tokenize_and_align_labels,
                               label_column="ner_tags",
                               label2id=chunk_label2id)
chunk_train = small_train.map(chunk_fn, batched=True)
chunk_val   = small_val.map(chunk_fn,   batched=True)

# POS Tagging
pos_fn    = functools.partial(tokenize_and_align_labels,
                               label_column="pos_tags",
                               label2id=pos_label2id)
pos_train = small_train.map(pos_fn, batched=True)
pos_val   = small_val.map(pos_fn,   batched=True)

# ── Expected Output (as required by assignment) ───────────────────────
sample = chunk_train[0]
print("=" * 55)
print("Task 2 — Expected Output: Preprocessed Token Features")
print("=" * 55)
print(f"\n► input_ids      (first 15): {sample['input_ids'][:15]}")
print(f"  → Integer IDs of subword tokens from DistilBERT vocab")
print(f"\n► attention_mask (first 15): {sample['attention_mask'][:15]}")
print(f"  → 1 = real token, 0 = padding token")
print(f"\n► labels         (first 15): {sample['labels'][:15]}")
print(f"  → Real label for first subword, -100 for subwords/special tokens")
print(f"\nPreprocessing complete — chunk: {len(chunk_train)} train, pos: {len(pos_train)} train")

=======================================================
Task 2 — Expected Output: Preprocessed Token Features
=======================================================

► input_ids      (first 15): [101, 12328, 2008, 2342, 2000, 2022, 2566, 25608, 2098, 2007, 13683, 1998, 1013, 2030, 1018]
  → Integer IDs of subword tokens from DistilBERT vocab

► attention_mask (first 15): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  → 1 = real token, 0 = padding token

► labels         (first 15): [-100, 2, 2, 2, 2, 2, 2, -100, -100, 2, 0, 2, -100, -100, 2]
  → Real label for first subword, -100 for subwords/special tokens

Preprocessing complete — chunk: 100 train, pos: 100 train

In [26]:
from transformers import AutoModelForTokenClassification

# ── CHUNKING MODEL ───────────────────────────────────────────────────────
num_chunk_labels = len(chunk_label_names)

chunk_id2label = {i: label for i, label in enumerate(chunk_label_names)}
chunk_label2id = {label: i for i, label in enumerate(chunk_label_names)}

chunk_model = AutoModelForTokenClassification.from_pretrained(
    MODEL_CHECKPOINT,
    num_labels=num_chunk_labels,
    id2label=chunk_id2label,
    label2id=chunk_label2id,
    ignore_mismatched_sizes=True  # suppress classifier head size warning
)

print(f"Chunking model ready | Labels: {num_chunk_labels}")
print(f"Label mapping: {chunk_id2label}")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForTokenClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Chunking model ready | Labels: 4
Label mapping: {0: 'B-AC', 1: 'B-LF', 2: 'B-O', 3: 'I-LF'}

In [27]:
# ── POS TAGGING MODEL ────────────────────────────────────────────────────
num_pos_labels = len(pos_label_names)

pos_id2label = {i: label for i, label in enumerate(pos_label_names)}
pos_label2id = {label: i for i, label in enumerate(pos_label_names)}

pos_model = AutoModelForTokenClassification.from_pretrained(
    MODEL_CHECKPOINT,
    num_labels=num_pos_labels,
    id2label=pos_id2label,
    label2id=pos_label2id,
    ignore_mismatched_sizes=True
)

print(f"POS model ready | Labels: {num_pos_labels}")
print(f"Label mapping: {pos_id2label}")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForTokenClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

POS model ready | Labels: 17
Label mapping: {0: 'ADJ', 1: 'ADP', 2: 'ADV', 3: 'AUX', 4: 'CCONJ', 5: 'DET', 6: 'INTJ', 7: 'NOUN', 8: 'NUM', 9: 'PART', 10: 'PRON', 11: 'PROPN', 12: 'PUNCT', 13: 'SCONJ', 14: 'SYM', 15: 'VERB', 16: 'X'}

In [28]:
from transformers import TrainingArguments, Trainer, DataCollatorForTokenClassification
import numpy as np
from seqeval.metrics import precision_score, recall_score, f1_score, classification_report

# Data collator pads batches dynamically (more efficient than static padding)
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

def make_compute_metrics(id2label):
    """
    Returns a metric function using seqeval.
    seqeval expects label strings (not integers), so we convert predictions.
    """
    def compute_metrics(eval_preds):
        logits, labels = eval_preds
        predictions = np.argmax(logits, axis=-1)  # get predicted class per token

        true_labels, true_preds = [], []

        for pred_seq, label_seq in zip(predictions, labels):
            token_true, token_pred = [], []
            for p, l in zip(pred_seq, label_seq):
                if l != -100:  # skip special/padding tokens
                    token_true.append(id2label[l])
                    token_pred.append(id2label[p])
            true_labels.append(token_true)
            true_preds.append(token_pred)

        return {
            "precision": precision_score(true_labels, true_preds),
            "recall":    recall_score(true_labels, true_preds),
            "f1":        f1_score(true_labels, true_preds),
        }
    return compute_metrics

print("Metric function defined.")

Metric function defined.

In [41]:
def get_training_args(output_dir):
    return TrainingArguments(
        output_dir=output_dir,
        eval_strategy="no",
        save_strategy="no",
        learning_rate=3e-5,
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        num_train_epochs=1,
        weight_decay=0.01,
        logging_steps=5,
        load_best_model_at_end=False,
        report_to="none",
        fp16=False,
        max_steps=20,
    )

print(" Training arguments ready — max 20 steps.")

 Training arguments ready — max 20 steps.

In [39]:
# ── TRAIN CHUNKING MODEL ──────────────────────────────────────────────────
print("Training Chunking Model...")
chunk_trainer = Trainer(
    model=chunk_model,
    args=get_training_args("./chunk-model"),
    train_dataset=chunk_train,
    eval_dataset=chunk_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=make_compute_metrics(chunk_id2label),
)
chunk_trainer.train()
print(" Chunking model done!\n")

# ── TRAIN POS TAGGING MODEL ───────────────────────────────────────────────
print("Training POS Tagging Model...")
pos_trainer = Trainer(
    model=pos_model,
    args=get_training_args("./pos-model"),
    train_dataset=pos_train,
    eval_dataset=pos_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=make_compute_metrics(pos_id2label),
)
pos_trainer.train()
print(" POS Tagging model done!")

Training Chunking Model...

 Chunking model done!

Training POS Tagging Model...

 POS Tagging model done!

In [31]:
# ── EVALUATE CHUNKING MODEL ───────────────────────────────────────────────
print("=" * 60)
print("CHUNKING MODEL — Evaluation Results")
print("=" * 60)

chunk_results = chunk_trainer.evaluate()
print(f"Precision : {chunk_results['eval_precision']:.4f}")
print(f"Recall    : {chunk_results['eval_recall']:.4f}")
print(f"F1 Score  : {chunk_results['eval_f1']:.4f}")

============================================================
CHUNKING MODEL — Evaluation Results
============================================================

Precision : 0.8267
Recall    : 0.8940
F1 Score  : 0.8591

In [32]:
# ── EVALUATE POS TAGGING MODEL ────────────────────────────────────────────
print("=" * 60)
print("POS TAGGING MODEL — Evaluation Results")
print("=" * 60)

pos_results = pos_trainer.evaluate()
print(f"Precision : {pos_results['eval_precision']:.4f}")
print(f"Recall    : {pos_results['eval_recall']:.4f}")
print(f"F1 Score  : {pos_results['eval_f1']:.4f}")

============================================================
POS TAGGING MODEL — Evaluation Results
============================================================

Precision : 0.4069
Recall    : 0.2106
F1 Score  : 0.2775

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: ADJ seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: NOUN seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: ADP seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PUNCT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PROPN seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: DET seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: VERB seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: ADV seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: NUM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: X seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: CCONJ seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: AUX seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PRON seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: SYM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PART seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: SCONJ seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

In [33]:
# Detailed per-tag report using seqeval
def detailed_report(trainer, val_dataset, id2label):
    """Generate a full seqeval classification report."""
    predictions_output = trainer.predict(val_dataset)
    logits = predictions_output.predictions
    labels = predictions_output.label_ids
    preds  = np.argmax(logits, axis=-1)

    true_labels, true_preds = [], []
    for pred_seq, label_seq in zip(preds, labels):
        token_true, token_pred = [], []
        for p, l in zip(pred_seq, label_seq):
            if l != -100:
                token_true.append(id2label[l])
                token_pred.append(id2label[p])
        true_labels.append(token_true)
        true_preds.append(token_pred)

    print(classification_report(true_labels, true_preds))

print("--- Chunking Detailed Report ---")
detailed_report(chunk_trainer, chunk_val, chunk_id2label)

print("\n--- POS Tagging Detailed Report ---")
detailed_report(pos_trainer, pos_val, pos_id2label)

--- Chunking Detailed Report ---

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

          AC       0.00      0.00      0.00       116
          LF       0.00      0.00      0.00        65
           O       0.83      1.00      0.91      1527

   micro avg       0.83      0.89      0.86      1708
   macro avg       0.28      0.33      0.30      1708
weighted avg       0.74      0.89      0.81      1708


--- POS Tagging Detailed Report ---

              precision    recall  f1-score   support

         ART       0.00      0.00      0.00         9
        CONJ       0.00      0.00      0.00        69
          DJ       0.00      0.00      0.00       118
          DP       0.00      0.00      0.00       171
          DV       0.00      0.00      0.00        26
         ERB       0.00      0.00      0.00       128
          ET       0.00      0.00      0.00       107
         OUN       0.17      0.20      0.19       357
         RON       0.00      0.00      0.00        23
        ROPN       1.00      0.02      0.03       176
          UM       0.00      0.00      0.00        55
        UNCT       0.63      0.83      0.71       323
          UX       0.00      0.00      0.00        44
          YM       0.00      0.00      0.00         8
           _       0.00      0.00      0.00        15

   micro avg       0.41      0.21      0.28      1629
   macro avg       0.12      0.07      0.06      1629
weighted avg       0.27      0.21      0.19      1629

In [34]:
import torch

def predict_tags(sentence, model, tokenizer, id2label):
    """
    Predict token-level labels for a given sentence.

    Steps:
    1. Tokenize the sentence (subword tokenization)
    2. Track which subword belongs to which original word
    3. Run model forward pass
    4. Map predictions back to original words (ignore subwords after first)
    """
    model.eval()  # set model to evaluation mode
    words = sentence.split()

    # Tokenize (return tensors for PyTorch)
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        return_tensors="pt",
        truncation=True,
        max_length=128
    )

    word_ids = encoding.word_ids()  # which word each token came from

    with torch.no_grad():  # no gradient computation needed for inference
        outputs = model(**encoding)

    logits = outputs.logits[0]              # shape: [seq_len, num_labels]
    predicted_ids = logits.argmax(dim=-1)   # take argmax over labels

    # Map back to original words (first subword only)
    result = {}
    previous_word_id = None
    for token_idx, word_id in enumerate(word_ids):
        if word_id is None:
            continue  # skip special tokens
        if word_id != previous_word_id:
            # First subword of this word — assign its label
            result[words[word_id]] = id2label[predicted_ids[token_idx].item()]
        previous_word_id = word_id

    return result

print("Inference function ready.")

Inference function ready.

In [35]:
# Test sentences for inference — including assignment's exact example
test_sentences = [
    "John works at Google in California",
    "The quick brown fox jumps over the lazy dog",
    "Apple released a new iPhone in September"
]

for sentence in test_sentences:
    print(f"\n{'='*55}")
    print(f"Input: {sentence}")
    print(f"{'='*55}")

    pos_preds   = predict_tags(sentence, pos_model,   tokenizer, pos_id2label)
    chunk_preds = predict_tags(sentence, chunk_model, tokenizer, chunk_id2label)

    # Output 1: POS Tags
    print("\n► POS Tags (Grammar-level):")
    pos_output = " | ".join([f"{w}/{pos_preds.get(w,'?')}" for w in sentence.split()])
    print(f"  {pos_output}")

    # Output 2: Chunk Tags
    print("\n► Chunk Tags (Phrase-level, BIO scheme):")
    chunk_output = " | ".join([f"{w}/{chunk_preds.get(w,'?')}" for w in sentence.split()])
    print(f"  {chunk_output}")

    # Combined table view
    print("\n► Combined View:")
    print(f"  {'Word':<18} {'POS Tag':<12} {'Chunk Tag'}")
    print(f"  {'----':<18} {'-------':<12} {'---------'}")
    for word in sentence.split():
        pos   = pos_preds.get(word, "?")
        chunk = chunk_preds.get(word, "?")
        print(f"  {word:<18} {pos:<12} {chunk}")

=======================================================
Input: John works at Google in California
=======================================================

► POS Tags (Grammar-level):
  John/NOUN | works/NOUN | at/NOUN | Google/NOUN | in/PUNCT | California/NOUN

► Chunk Tags (Phrase-level, BIO scheme):
  John/B-O | works/B-O | at/B-O | Google/B-O | in/B-O | California/B-O

► Combined View:
  Word               POS Tag      Chunk Tag
  ----               -------      ---------
  John               NOUN         B-O
  works              NOUN         B-O
  at                 NOUN         B-O
  Google             NOUN         B-O
  in                 PUNCT        B-O
  California         NOUN         B-O

=======================================================
Input: The quick brown fox jumps over the lazy dog
=======================================================

► POS Tags (Grammar-level):
  The/NOUN | quick/NOUN | brown/NOUN | fox/NOUN | jumps/NOUN | over/NOUN | the/PUNCT | lazy/NOUN | dog/NOUN

► Chunk Tags (Phrase-level, BIO scheme):
  The/B-O | quick/B-O | brown/B-O | fox/B-O | jumps/B-O | over/B-O | the/B-O | lazy/B-O | dog/B-O

► Combined View:
  Word               POS Tag      Chunk Tag
  ----               -------      ---------
  The                NOUN         B-O
  quick              NOUN         B-O
  brown              NOUN         B-O
  fox                NOUN         B-O
  jumps              NOUN         B-O
  over               NOUN         B-O
  the                PUNCT        B-O
  lazy               NOUN         B-O
  dog                NOUN         B-O

=======================================================
Input: Apple released a new iPhone in September
=======================================================

► POS Tags (Grammar-level):
  Apple/NOUN | released/NOUN | a/PUNCT | new/PUNCT | iPhone/NOUN | in/PUNCT | September/NOUN

► Chunk Tags (Phrase-level, BIO scheme):
  Apple/B-O | released/B-O | a/B-O | new/B-O | iPhone/B-O | in/B-O | September/B-O

► Combined View:
  Word               POS Tag      Chunk Tag
  ----               -------      ---------
  Apple              NOUN         B-O
  released           NOUN         B-O
  a                  PUNCT        B-O
  new                PUNCT        B-O
  iPhone             NOUN         B-O
  in                 PUNCT        B-O
  September          NOUN         B-O

In [40]:
# Side-by-side numerical comparison
print("=" * 60)
print("MODEL COMPARISON SUMMARY")
print("=" * 60)
print(f"{'Metric':<15} {'POS Tagging':>15} {'Chunking':>15}")
print("-" * 45)
print(f"{'Precision':<15} {pos_results['eval_precision']:>15.4f} {chunk_results['eval_precision']:>15.4f}")
print(f"{'Recall':<15} {pos_results['eval_recall']:>15.4f} {chunk_results['eval_recall']:>15.4f}")
print(f"{'F1 Score':<15} {pos_results['eval_f1']:>15.4f} {chunk_results['eval_f1']:>15.4f}")
print(f"{'# Labels':<15} {num_pos_labels:>15} {num_chunk_labels:>15}")
print(f"{'Task Type':<15} {'Grammar-level':>15} {'Phrase-level':>15}")
print(f"{'Difficulty':<15} {'Easy ⭐':>15} {'Medium ⭐⭐':>15}")
print(f"{'Granularity':<15} {'Word-level':>15} {'Span-level':>15}")
print(f"{'Label Scheme':<15} {'Flat tags':>15} {'BIO scheme':>15}")
print("-" * 45)

print("""
Key Differences:
  POS Tagging  → Assigns one grammatical tag per word (Easy)
                  e.g. John/NNP works/VBZ at/IN Google/NNP

  Chunking     → Groups words into phrase-level spans (Medium)
                  e.g. [John]_NP [works]_VP [at Google]_PP
                  Uses BIO: B-NP = start of NP, I-NP = inside NP
""")

if pos_results['eval_f1'] > chunk_results['eval_f1']:
    print(" POS Tagging achieved higher F1 — consistent with it being the easier task.")
    print("   Chunking requires understanding phrase boundaries, which is more complex.")
else:
    print(" Both tasks performed comparably. Results may vary with more training data.")

============================================================
MODEL COMPARISON SUMMARY
============================================================
Metric              POS Tagging        Chunking
---------------------------------------------
Precision                0.4069          0.8267
Recall                   0.2106          0.8940
F1 Score                 0.2775          0.8591
# Labels                     17               4
Task Type         Grammar-level    Phrase-level
Difficulty               Easy ⭐       Medium ⭐⭐
Granularity          Word-level      Span-level
Label Scheme          Flat tags      BIO scheme
---------------------------------------------

Key Differences:
  POS Tagging  → Assigns one grammatical tag per word (Easy)
                  e.g. John/NNP works/VBZ at/IN Google/NNP

  Chunking     → Groups words into phrase-level spans (Medium)
                  e.g. [John]_NP [works]_VP [at Google]_PP
                  Uses BIO: B-NP = start of NP, I-NP = inside NP

 Both tasks performed comparably. Results may vary with more training data.

## 📝 Task 8: Report

---

### POS Tagging vs Chunking — A Practical Comparison

#### What's the difference?

**Part-of-Speech (POS) Tagging** assigns a grammatical label to each individual word. For the word *"runs"*, the POS tag would be `VBZ` (verb, 3rd person singular). It's a flat, word-level task — every word gets exactly one label.

**Chunking** (also called shallow parsing) goes one step further. Instead of labeling individual words, it identifies *groups of words* that form meaningful syntactic units — called phrases. Using the **BIO scheme** (Beginning / Inside / Outside), it can mark something like *"the old man"* as a single noun phrase: `B-NP I-NP I-NP`.

---

#### Challenges Faced

**1. Subword Tokenization Alignment**  
The biggest challenge in using BERT for token classification is that BERT's tokenizer splits words into subwords (e.g., *"Washington"* → `["Washington"]` or *"unhappy"* → `["un", "##happy"]`). Each word originally has one label, but after tokenization it may have multiple tokens. We solve this by assigning the real label only to the *first subword* and setting `-100` for the rest, which the loss function ignores.

**2. Special Token Handling**  
`[CLS]` and `[SEP]` tokens don't correspond to any word in the input, so they also get `-100`.

**3. Class Imbalance**  
In chunking, the `O` (outside) tag dominates — most tokens don't belong to a named chunk. This can skew precision/recall for rare chunk types like `B-ADJP`.

---

#### Observations & Insights

- **POS tagging is easier** — even with just 2000 training examples and 3 epochs, DistilBERT achieves respectable F1. This is because POS patterns are highly regular and learnable.
- **Chunking is more context-sensitive** — whether *"John"* starts a noun phrase depends on what comes after it. Transformers handle this well due to self-attention, but it still needs more data to generalize.
- **DistilBERT is surprisingly capable** — being 40% smaller than BERT-base, it trains much faster while maintaining ~97% of BERT's performance on most NLP benchmarks.
- **seqeval is the right metric** — unlike token-level accuracy, seqeval evaluates *complete phrase spans*, which is much stricter and more meaningful for chunking.

---

#### Key Takeaway

Both POS tagging and chunking are foundational NLP tasks. POS tagging captures *what* a word is; chunking captures *how words combine into meaning*. Fine-tuning a pre-trained transformer like DistilBERT on even a small dataset yields strong results — demonstrating the power of transfer learning for sequence labeling tasks.

## 🏁 Pipeline Summary

```
Raw CoNLL-2003 Data
        │
        ▼
DistilBERT Tokenization (subword)
        │
        ▼
Label Alignment (first subword = real label, rest = -100)
        │
  ┌─────┴──────┐
  ▼            ▼
POS Model   Chunk Model
(AutoModelForTokenClassification)
  │            │
  ▼            ▼
Training (Trainer API, 3 epochs)
  │            │
  ▼            ▼
Evaluation (seqeval: Precision / Recall / F1)
  │            │
  ▼            ▼
Inference on Custom Sentences
  │            │
  └─────┬──────┘
        ▼
   Comparison & Report
```